from config import NOTION_TOKEN, DB_INTERVENTIONS_ID, DB_INVOICES_ID

print("Token:", NOTION_TOKEN[:10], "...")
print("DB_INTERVENTIONS_ID:", DB_INTERVENTIONS_ID)
print("DB_INVOICES_ID:", DB_INVOICES_ID)
